import { PERMISSIONS, type PermissionValue } from '@tiles-erp/config';

/** Permission required to open each sidebar destination. Mirrors its primary read endpoint. */
export const MENU_PERMISSIONS: Record<string, PermissionValue> = {
  '/': PERMISSIONS.DASHBOARD_READ,
  '/quotations': PERMISSIONS.QUOTATION_READ,
  '/sales-orders': PERMISSIONS.SALES_ORDER_READ,
  '/sales-invoices': PERMISSIONS.SALES_INVOICE_READ,
  '/sales-returns': PERMISSIONS.SALES_INVOICE_READ,
  '/collections': PERMISSIONS.RECEIPT_READ,
  '/outstanding': PERMISSIONS.CUSTOMER_LEDGER_READ,
  '/customer-ledger': PERMISSIONS.CUSTOMER_LEDGER_READ,
  '/purchase-orders': PERMISSIONS.PURCHASE_ORDER_READ,
  '/goods-receipts': PERMISSIONS.GRN_READ,
  '/purchase-invoices': PERMISSIONS.PURCHASE_INVOICE_READ,
  '/purchase-returns': PERMISSIONS.PURCHASE_RETURN_READ,
  '/supplier-payments': PERMISSIONS.SUPPLIER_PAYMENT_READ,
  '/payables': PERMISSIONS.SUPPLIER_LEDGER_READ,
  '/supplier-ledger': PERMISSIONS.SUPPLIER_LEDGER_READ,
  '/stock': PERMISSIONS.STOCK_READ,
  '/stock/check': PERMISSIONS.STOCK_READ,
  '/stock/product-check': PERMISSIONS.STOCK_READ,
  '/stock/count': PERMISSIONS.STOCK_READ,
  '/stock/transfers': PERMISSIONS.STOCK_READ,
  '/stock/reports': PERMISSIONS.STOCK_READ,
  '/product-audit': PERMISSIONS.PRODUCT_READ,
  '/gate-passes': PERMISSIONS.GATE_PASS_READ,
  '/driver-cash': PERMISSIONS.DRIVER_CASH_READ,
  '/dispatch-reports': PERMISSIONS.DISPATCH_REPORT_READ,
  '/accounts': PERMISSIONS.CASH_BOOK_READ,
  '/cash-book': PERMISSIONS.CASH_BOOK_READ,
  '/day-close': PERMISSIONS.CASH_BOOK_READ,
  '/owner-statement': PERMISSIONS.CASH_BOOK_READ,
  '/expense-heads': PERMISSIONS.CASH_BOOK_READ,
  '/gst-summary': PERMISSIONS.GST_REPORT_READ,
  '/purchase-gst': PERMISSIONS.GST_REPORT_READ,
  '/profit': PERMISSIONS.PROFIT_REPORT_READ,
  '/reports/product-transactions': PERMISSIONS.PROFIT_REPORT_READ,
  '/reports/fast-moving': PERMISSIONS.PROFIT_REPORT_READ,
  '/reports/product-sales': PERMISSIONS.PROFIT_REPORT_READ,
  '/reports/salesman-incentives': PERMISSIONS.PROFIT_REPORT_READ,
  '/products/incentives': PERMISSIONS.PRODUCT_UPDATE,
  '/reports/salesman-sales': PERMISSIONS.PROFIT_REPORT_READ,
  '/crm': PERMISSIONS.CRM_LEAD_READ,
  '/crm/campaigns': PERMISSIONS.CRM_CAMPAIGN_READ,
  '/crm/visits': PERMISSIONS.CRM_VISIT_READ,
  '/customers': PERMISSIONS.CUSTOMER_READ,
  '/suppliers': PERMISSIONS.SUPPLIER_READ,
  '/products': PERMISSIONS.PRODUCT_READ,
  '/products/rates': PERMISSIONS.PRICE_READ,
  '/products/prices': PERMISSIONS.PRICE_READ,
  '/catalog/categories': PERMISSIONS.CATEGORY_READ,
  '/catalog/brands': PERMISSIONS.BRAND_READ,
  '/catalog/series': PERMISSIONS.SERIES_READ,
  '/catalog/collections': PERMISSIONS.COLLECTION_READ,
  '/transporters': PERMISSIONS.TRANSPORTER_READ,
  '/vehicles': PERMISSIONS.VEHICLE_READ,
  '/drivers': PERMISSIONS.DRIVER_READ,
  '/users': PERMISSIONS.USER_READ,
  '/roles': PERMISSIONS.ROLE_READ,
  '/departments': PERMISSIONS.DEPARTMENT_READ,
  '/organization/companies': PERMISSIONS.COMPANY_READ,
  '/organization/branches': PERMISSIONS.BRANCH_READ,
  '/organization/godowns': PERMISSIONS.GODOWN_READ,
  '/organization/gates': PERMISSIONS.GATE_READ,
  '/organization/racks': PERMISSIONS.RACK_READ,
  '/number-series': PERMISSIONS.SETTINGS_MANAGE,
  '/portal-access': PERMISSIONS.PORTAL_ACCOUNT_MANAGE,
  '/audit': PERMISSIONS.AUDIT_READ,
  '/sixorbit': PERMISSIONS.SIXORBIT_CONFIGURE,
  '/sixorbit/products': PERMISSIONS.SIXORBIT_READ,
  '/sixorbit/sync-log': PERMISSIONS.SIXORBIT_READ,
  '/settings': PERMISSIONS.SETTINGS_MANAGE,
};

export function canSeeMenu(path: string, permissions: readonly string[], roles: readonly string[]): boolean {
  const required = MENU_PERMISSIONS[path];
  return Boolean(required && (roles.includes('SUPER_ADMIN') || permissions.includes(required)));
}
